
Q_PROPERTY(float RTC                    READ RTC                NOTIFY onHolleyDataChanged) const float& RTC()                  {return m_data[0];}
Q_PROPERTY(float RPM                    READ RPM                NOTIFY onHolleyDataChanged) const float& RPM()                  {return m_data[1];}
Q_PROPERTY(float Inj_PW                 READ Inj_PW             NOTIFY onHolleyDataChanged) const float& Inj_PW()               {return m_data[2];}
Q_PROPERTY(float Duty_Cycle             READ Duty_Cycle         NOTIFY onHolleyDataChanged) const float& Duty_Cycle()           {return m_data[3];}
Q_PROPERTY(float CL_Comp                READ CL_Comp            NOTIFY onHolleyDataChanged) const float& CL_Comp()              {return m_data[4];}
Q_PROPERTY(float Target_AFR             READ Target_AFR         NOTIFY onHolleyDataChanged) const float& Target_AFR()           {return m_data[5];}
Q_PROPERTY(float ARF_Left               READ ARF_Left           NOTIFY onHolleyDataChanged) const float& ARF_Left()             {return m_data[6];}
Q_PROPERTY(float AFR_Right              READ AFR_Right          NOTIFY onHolleyDataChanged) const float& AFR_Right()            {return m_data[7];}
Q_PROPERTY(float AFR_Average            READ AFR_Average        NOTIFY onHolleyDataChanged) const float& AFR_Average()          {return m_data[8];}
Q_PROPERTY(float Air_Temp_Enr           READ Air_Temp_Enr       NOTIFY onHolleyDataChanged) const float& Air_Temp_Enr()         {return m_data[9];}
Q_PROPERTY(float Coolant_Enr            READ Coolant_Enr        NOTIFY onHolleyDataChanged) const float& Coolant_Enr()          {return m_data[10];}
Q_PROPERTY(float Coolant_AFR_Offset     READ Coolant_AFR_Offset NOTIFY onHolleyDataChanged) const float& Coolant_AFR_Offset()   {return m_data[11];}
Q_PROPERTY(float Afterstart_Enr         READ Afterstart_Enr     NOTIFY onHolleyDataChanged) const float& Afterstart_Enr()       {return m_data[12];}
Q_PROPERTY(float Current_Learn          READ Current_Learn      NOTIFY onHolleyDataChanged) const float& Current_Learn()        {return m_data[13];}
Q_PROPERTY(float CL_Status              READ CL_Status          NOTIFY onHolleyDataChanged) const float& CL_Status()            {return m_data[14];}
Q_PROPERTY(float Learn_Status           READ Learn_Status       NOTIFY onHolleyDataChanged) const float& Learn_Status()         {return m_data[15];}
Q_PROPERTY(float Fuel_Economy           READ Fuel_Economy       NOTIFY onHolleyDataChanged) const float& Fuel_Economy()         {return m_data[16];}
Q_PROPERTY(float Fuel_Flow              READ Fuel_Flow          NOTIFY onHolleyDataChanged) const float& Fuel_Flow()            {return m_data[17];}
Q_PROPERTY(float MAP_RoC                READ MAP_RoC            NOTIFY onHolleyDataChanged) const float& MAP_RoC()              {return m_data[18];}
Q_PROPERTY(float TPS_RoC                READ TPS_RoC            NOTIFY onHolleyDataChanged) const float& TPS_RoC()              {return m_data[19];}
Q_PROPERTY(float Tuning_Change          READ Tuning_Change      NOTIFY onHolleyDataChanged) const float& Tuning_Change()        {return m_data[20];}
Q_PROPERTY(float Estimated_VE           READ Estimated_VE       NOTIFY onHolleyDataChanged) const float& Estimated_VE()         {return m_data[21];}
Q_PROPERTY(float Ignition_Timing        READ Ignition_Timing    NOTIFY onHolleyDataChanged) const float& Ignition_Timing()      {return m_data[22];}
Q_PROPERTY(float Knock_Retard           READ Knock_Retard       NOTIFY onHolleyDataChanged) const float& Knock_Retard()         {return m_data[23];}
Q_PROPERTY(float Knock_Level            READ Knock_Level        NOTIFY onHolleyDataChanged) const float& Knock_Level()          {return m_data[24];}
Q_PROPERTY(float Spark_Pad2             READ Spark_Pad2         NOTIFY onHolleyDataChanged) const float& Spark_Pad2()           {return m_data[25];}
Q_PROPERTY(float IAC_Position           READ IAC_Position       NOTIFY onHolleyDataChanged) const float& IAC_Position()         {return m_data[26];}
Q_PROPERTY(float Idle_Pad1              READ Idle_Pad1          NOTIFY onHolleyDataChanged) const float& Idle_Pad1()            {return m_data[27];}
Q_PROPERTY(float MAP                    READ MAP                NOTIFY onHolleyDataChanged) const float& MAP()                  {return m_data[28];}
Q_PROPERTY(float TPS                    READ TPS                NOTIFY onHolleyDataChanged) const float& TPS()                  {return m_data[29];}
Q_PROPERTY(float MAT                    READ MAT                NOTIFY onHolleyDataChanged) const float& MAT()                  {return m_data[30];}
Q_PROPERTY(float CTS                    READ CTS                NOTIFY onHolleyDataChanged) const float& CTS()                  {return m_data[31];}
Q_PROPERTY(float Baro                   READ Baro               NOTIFY onHolleyDataChanged) const float& Baro()                 {return m_data[32];}
Q_PROPERTY(float Battery                READ Battery            NOTIFY onHolleyDataChanged) const float& Battery()              {return m_data[33];}
Q_PROPERTY(float Oil_Pressure           READ Oil_Pressure       NOTIFY onHolleyDataChanged) const float& Oil_Pressure()         {return m_data[34];}
Q_PROPERTY(float Fuel_Pressure          READ Fuel_Pressure      NOTIFY onHolleyDataChanged) const float& Fuel_Pressure()        {return m_data[35];}
Q_PROPERTY(float Pedal_Position         READ Pedal_Position     NOTIFY onHolleyDataChanged) const float& Pedal_Position()       {return m_data[36];}
Q_PROPERTY(float Main_Rev_Limit         READ Main_Rev_Limit     NOTIFY onHolleyDataChanged) const float& Main_Rev_Limit()       {return m_data[37];}
Q_PROPERTY(float Rev_Limit_1            READ Rev_Limit_1        NOTIFY onHolleyDataChanged) const float& Rev_Limit_1()          {return m_data[38];}
Q_PROPERTY(float Rev_Limit_2            READ Rev_Limit_2        NOTIFY onHolleyDataChanged) const float& Rev_Limit_2()          {return m_data[39];}
Q_PROPERTY(float AC_Kick                READ AC_Kick            NOTIFY onHolleyDataChanged) const float& AC_Kick()              {return m_data[40];}
Q_PROPERTY(float Timing_Retard_1        READ Timing_Retard_1    NOTIFY onHolleyDataChanged) const float& Timing_Retard_1()      {return m_data[41];}
Q_PROPERTY(float Timing_Retard_2        READ Timing_Retard_2    NOTIFY onHolleyDataChanged) const float& Timing_Retard_2()      {return m_data[42];}
Q_PROPERTY(float Timing_Retard_3        READ Timing_Retard_3    NOTIFY onHolleyDataChanged) const float& Timing_Retard_3()      {return m_data[43];}
Q_PROPERTY(float Fan_1                  READ Fan_1              NOTIFY onHolleyDataChanged) const float& Fan_1()                {return m_data[44];}
Q_PROPERTY(float Fan_2                  READ Fan_2              NOTIFY onHolleyDataChanged) const float& Fan_2()                {return m_data[45];}
Q_PROPERTY(float Second_Feul_Pump       READ Second_Feul_Pump   NOTIFY onHolleyDataChanged) const float& Second_Feul_Pump()     {return m_data[46];}
Q_PROPERTY(float AC_Shutdown            READ AC_Shutdown        NOTIFY onHolleyDataChanged) const float& AC_Shutdown()          {return m_data[47];}
Q_PROPERTY(float TCC_Lockup             READ TCC_Lockup         NOTIFY onHolleyDataChanged) const float& TCC_Lockup()           {return m_data[48];}
Q_PROPERTY(float Sensor_Warning         READ Sensor_Warning     NOTIFY onHolleyDataChanged) const float& Sensor_Warning()       {return m_data[49];}
Q_PROPERTY(float Sensor_Caution         READ Sensor_Caution     NOTIFY onHolleyDataChanged) const float& Sensor_Caution()       {return m_data[50];}
Q_PROPERTY(float Base_Fuel_lb_hr        READ Base_Fuel_lb_hr    NOTIFY onHolleyDataChanged) const float& Base_Fuel_lb_hr()      {return m_data[51];}
Q_PROPERTY(float Base_Fuel_VE           READ Base_Fuel_VE       NOTIFY onHolleyDataChanged) const float& Base_Fuel_VE()         {return m_data[52];}
Q_PROPERTY(float Base_Timing            READ Base_Timing        NOTIFY onHolleyDataChanged) const float& Base_Timing()          {return m_data[53];}
Q_PROPERTY(float Base_Target_AFR        READ Base_Target_AFR    NOTIFY onHolleyDataChanged) const float& Base_Target_AFR()      {return m_data[54];}
Q_PROPERTY(float Base_Ign_Dwell         READ Base_Ign_Dwell     NOTIFY onHolleyDataChanged) const float& Base_Ign_Dwell()       {return m_data[55];}
Q_PROPERTY(float Vol_Comp_Ign_Dwell     READ Vol_Comp_Ign_Dwell NOTIFY onHolleyDataChanged) const float& Vol_Comp_Ign_Dwell()   {return m_data[56];}
Q_PROPERTY(float Inj_End_Angle          READ Inj_End_Angle      NOTIFY onHolleyDataChanged) const float& Inj_End_Angle()        {return m_data[57];}
Q_PROPERTY(float ECU_Log_Trigger        READ ECU_Log_Trigger    NOTIFY onHolleyDataChanged) const float& ECU_Log_Trigger()      {return m_data[58];}
Q_PROPERTY(float Timing_vs_Air          READ Timing_vs_Air      NOTIFY onHolleyDataChanged) const float& Timing_vs_Air()        {return m_data[59];}
Q_PROPERTY(float Timing_vs_Cool         READ Timing_vs_Cool     NOTIFY onHolleyDataChanged) const float& Timing_vs_Cool()       {return m_data[60];}
Q_PROPERTY(float Status_1               READ Status_1           NOTIFY onHolleyDataChanged) const float& Status_1()             {return m_data[61];}
Q_PROPERTY(float Status_2               READ Status_2           NOTIFY onHolleyDataChanged) const float& Status_2()             {return m_data[62];}
Q_PROPERTY(float Status_3               READ Status_3           NOTIFY onHolleyDataChanged) const float& Status_3()             {return m_data[63];}
Q_PROPERTY(float Status_4               READ Status_4           NOTIFY onHolleyDataChanged) const float& Status_4()             {return m_data[64];}
Q_PROPERTY(float Status_5               READ Status_5           NOTIFY onHolleyDataChanged) const float& Status_5()             {return m_data[65];}
Q_PROPERTY(float Status_6               READ Status_6           NOTIFY onHolleyDataChanged) const float& Status_6()             {return m_data[66];}
Q_PROPERTY(float Status_7               READ Status_7           NOTIFY onHolleyDataChanged) const float& Status_7()             {return m_data[67];}
Q_PROPERTY(float Status_8               READ Status_8           NOTIFY onHolleyDataChanged) const float& Status_8()             {return m_data[68];}
Q_PROPERTY(float Injector_1_PPH         READ Injector_1_PPH     NOTIFY onHolleyDataChanged) const float& Injector_1_PPH()       {return m_data[69];}
Q_PROPERTY(float Injector_2_PPH         READ Injector_2_PPH     NOTIFY onHolleyDataChanged) const float& Injector_2_PPH()       {return m_data[70];}
Q_PROPERTY(float Injector_3_PPH         READ Injector_3_PPH     NOTIFY onHolleyDataChanged) const float& Injector_3_PPH()       {return m_data[71];}
Q_PROPERTY(float Injector_4_PPH         READ Injector_4_PPH     NOTIFY onHolleyDataChanged) const float& Injector_4_PPH()       {return m_data[72];}
Q_PROPERTY(float Injector_5_PPH         READ Injector_5_PPH     NOTIFY onHolleyDataChanged) const float& Injector_5_PPH()       {return m_data[73];}
Q_PROPERTY(float Injector_6_PPH         READ Injector_6_PPH     NOTIFY onHolleyDataChanged) const float& Injector_6_PPH()       {return m_data[74];}
Q_PROPERTY(float Injector_7_PPH         READ Injector_7_PPH     NOTIFY onHolleyDataChanged) const float& Injector_7_PPH()       {return m_data[75];}
Q_PROPERTY(float Injector_8_PPH         READ Injector_8_PPH     NOTIFY onHolleyDataChanged) const float& Injector_8_PPH()       {return m_data[76];}
Q_PROPERTY(float Injector_9_PPH         READ Injector_9_PPH     NOTIFY onHolleyDataChanged) const float& Injector_9_PPH()       {return m_data[77];}
Q_PROPERTY(float Injector_10_PPH        READ Injector_10_PPH    NOTIFY onHolleyDataChanged) const float& Injector_10_PPH()      {return m_data[78];}
Q_PROPERTY(float Injector_11_PPH        READ Injector_11_PPH    NOTIFY onHolleyDataChanged) const float& Injector_11_PPH()      {return m_data[79];}
Q_PROPERTY(float Injector_12_PPH        READ Injector_12_PPH    NOTIFY onHolleyDataChanged) const float& Injector_12_PPH()      {return m_data[80];}
Q_PROPERTY(float Injector_1_PW          READ Injector_1_PW      NOTIFY onHolleyDataChanged) const float& Injector_1_PW()        {return m_data[81];}
Q_PROPERTY(float Injector_2_PW          READ Injector_2_PW      NOTIFY onHolleyDataChanged) const float& Injector_2_PW()        {return m_data[82];}
Q_PROPERTY(float Injector_3_PW          READ Injector_3_PW      NOTIFY onHolleyDataChanged) const float& Injector_3_PW()        {return m_data[83];}
Q_PROPERTY(float Injector_4_PW          READ Injector_4_PW      NOTIFY onHolleyDataChanged) const float& Injector_4_PW()        {return m_data[84];}
Q_PROPERTY(float Injector_5_PW          READ Injector_5_PW      NOTIFY onHolleyDataChanged) const float& Injector_5_PW()        {return m_data[85];}
Q_PROPERTY(float Injector_6_PW          READ Injector_6_PW      NOTIFY onHolleyDataChanged) const float& Injector_6_PW()        {return m_data[86];}
Q_PROPERTY(float Injector_7_PW          READ Injector_7_PW      NOTIFY onHolleyDataChanged) const float& Injector_7_PW()        {return m_data[87];}
Q_PROPERTY(float Injector_8_PW          READ Injector_8_PW      NOTIFY onHolleyDataChanged) const float& Injector_8_PW()        {return m_data[88];}
Q_PROPERTY(float Injector_9_PW          READ Injector_9_PW      NOTIFY onHolleyDataChanged) const float& Injector_9_PW()        {return m_data[89];}
Q_PROPERTY(float Injector_10_PW         READ Injector_10_PW     NOTIFY onHolleyDataChanged) const float& Injector_10_PW()       {return m_data[90];}
Q_PROPERTY(float Injector_11_PW         READ Injector_11_PW     NOTIFY onHolleyDataChanged) const float& Injector_11_PW()       {return m_data[91];}
Q_PROPERTY(float Injector_12_PW         READ Injector_12_PW     NOTIFY onHolleyDataChanged) const float& Injector_12_PW()       {return m_data[92];}
Q_PROPERTY(float Cyl_1_Fuel_Cor         READ Cyl_1_Fuel_Cor     NOTIFY onHolleyDataChanged) const float& Cyl_1_Fuel_Cor()       {return m_data[93];}
Q_PROPERTY(float Cyl_2_Fuel_Cor         READ Cyl_2_Fuel_Cor     NOTIFY onHolleyDataChanged) const float& Cyl_2_Fuel_Cor()       {return m_data[94];}
Q_PROPERTY(float Cyl_3_Fuel_Cor         READ Cyl_3_Fuel_Cor     NOTIFY onHolleyDataChanged) const float& Cyl_3_Fuel_Cor()       {return m_data[95];}
Q_PROPERTY(float Cyl_4_Fuel_Cor         READ Cyl_4_Fuel_Cor     NOTIFY onHolleyDataChanged) const float& Cyl_4_Fuel_Cor()       {return m_data[96];}
Q_PROPERTY(float Cyl_5_Fuel_Cor         READ Cyl_5_Fuel_Cor     NOTIFY onHolleyDataChanged) const float& Cyl_5_Fuel_Cor()       {return m_data[97];}
Q_PROPERTY(float Cyl_6_Fuel_Cor         READ Cyl_6_Fuel_Cor     NOTIFY onHolleyDataChanged) const float& Cyl_6_Fuel_Cor()       {return m_data[98];}
Q_PROPERTY(float Cyl_7_Fuel_Cor         READ Cyl_7_Fuel_Cor     NOTIFY onHolleyDataChanged) const float& Cyl_7_Fuel_Cor()       {return m_data[99];}
Q_PROPERTY(float Cyl_8_Fuel_Cor         READ Cyl_8_Fuel_Cor     NOTIFY onHolleyDataChanged) const float& Cyl_8_Fuel_Cor()       {return m_data[100];}
Q_PROPERTY(float Cyl_9_Fuel_Cor         READ Cyl_9_Fuel_Cor     NOTIFY onHolleyDataChanged) const float& Cyl_9_Fuel_Cor()       {return m_data[101];}
Q_PROPERTY(float Cyl_10_Fuel_Cor        READ Cyl_10_Fuel_Cor    NOTIFY onHolleyDataChanged) const float& Cyl_10_Fuel_Cor()      {return m_data[102];}
Q_PROPERTY(float Cyl_11_Fuel_Cor        READ Cyl_11_Fuel_Cor    NOTIFY onHolleyDataChanged) const float& Cyl_11_Fuel_Cor()      {return m_data[103];}
Q_PROPERTY(float Cyl_12_Fuel_Cor        READ Cyl_12_Fuel_Cor    NOTIFY onHolleyDataChanged) const float& Cyl_12_Fuel_Cor()      {return m_data[104];}
Q_PROPERTY(float Cyl_13_Fuel_Cor        READ Cyl_13_Fuel_Cor    NOTIFY onHolleyDataChanged) const float& Cyl_13_Fuel_Cor()      {return m_data[105];}
Q_PROPERTY(float Cyl_14_Fuel_Cor        READ Cyl_14_Fuel_Cor    NOTIFY onHolleyDataChanged) const float& Cyl_14_Fuel_Cor()      {return m_data[106];}
Q_PROPERTY(float Cyl_15_Fuel_Cor        READ Cyl_15_Fuel_Cor    NOTIFY onHolleyDataChanged) const float& Cyl_15_Fuel_Cor()      {return m_data[107];}
Q_PROPERTY(float Cyl_16_Fuel_Cor        READ Cyl_16_Fuel_Cor    NOTIFY onHolleyDataChanged) const float& Cyl_16_Fuel_Cor()      {return m_data[108];}
Q_PROPERTY(float Cyl_1_Timing_Cor       READ Cyl_1_Timing_Cor   NOTIFY onHolleyDataChanged) const float& Cyl_1_Timing_Cor()     {return m_data[109];}
Q_PROPERTY(float Cyl_2_Timing_Cor       READ Cyl_2_Timing_Cor   NOTIFY onHolleyDataChanged) const float& Cyl_2_Timing_Cor()     {return m_data[110];}
Q_PROPERTY(float Cyl_3_Timing_Cor       READ Cyl_3_Timing_Cor   NOTIFY onHolleyDataChanged) const float& Cyl_3_Timing_Cor()     {return m_data[111];}
Q_PROPERTY(float Cyl_4_Timing_Cor       READ Cyl_4_Timing_Cor   NOTIFY onHolleyDataChanged) const float& Cyl_4_Timing_Cor()     {return m_data[112];}
Q_PROPERTY(float Cyl_5_Timing_Cor       READ Cyl_5_Timing_Cor   NOTIFY onHolleyDataChanged) const float& Cyl_5_Timing_Cor()     {return m_data[113];}
Q_PROPERTY(float Cyl_6_Timing_Cor       READ Cyl_6_Timing_Cor   NOTIFY onHolleyDataChanged) const float& Cyl_6_Timing_Cor()     {return m_data[114];}
Q_PROPERTY(float Cyl_7_Timing_Cor       READ Cyl_7_Timing_Cor   NOTIFY onHolleyDataChanged) const float& Cyl_7_Timing_Cor()     {return m_data[115];}
Q_PROPERTY(float Cyl_8_Timing_Cor       READ Cyl_8_Timing_Cor   NOTIFY onHolleyDataChanged) const float& Cyl_8_Timing_Cor()     {return m_data[116];}
Q_PROPERTY(float Cyl_9_Timing_Cor       READ Cyl_9_Timing_Cor   NOTIFY onHolleyDataChanged) const float& Cyl_9_Timing_Cor()     {return m_data[117];}
Q_PROPERTY(float Cyl_10_Timing_Cor      READ Cyl_10_Timing_Cor  NOTIFY onHolleyDataChanged) const float& Cyl_10_Timing_Cor()    {return m_data[118];}
Q_PROPERTY(float Cyl_11_Timing_Cor      READ Cyl_11_Timing_Cor  NOTIFY onHolleyDataChanged) const float& Cyl_11_Timing_Cor()    {return m_data[119];}
Q_PROPERTY(float Cyl_12_Timing_Cor      READ Cyl_12_Timing_Cor  NOTIFY onHolleyDataChanged) const float& Cyl_12_Timing_Cor()    {return m_data[120];}
Q_PROPERTY(float Cyl_13_Timing_Cor      READ Cyl_13_Timing_Cor  NOTIFY onHolleyDataChanged) const float& Cyl_13_Timing_Cor()    {return m_data[121];}
Q_PROPERTY(float Cyl_14_Timing_Cor      READ Cyl_14_Timing_Cor  NOTIFY onHolleyDataChanged) const float& Cyl_14_Timing_Cor()    {return m_data[122];}
Q_PROPERTY(float Cyl_15_Timing_Cor      READ Cyl_15_Timing_Cor  NOTIFY onHolleyDataChanged) const float& Cyl_15_Timing_Cor()    {return m_data[123];}
Q_PROPERTY(float Cyl_16_Timing_Cor      READ Cyl_16_Timing_Cor  NOTIFY onHolleyDataChanged) const float& Cyl_16_Timing_Cor()    {return m_data[124];}
Q_PROPERTY(float DI_Target_FP           READ DI_Target_FP       NOTIFY onHolleyDataChanged) const float& DI_Target_FP()         {return m_data[125];}
Q_PROPERTY(float Boost_PSIG             READ Boost_PSIG         NOTIFY onHolleyDataChanged) const float& Boost_PSIG()           {return m_data[126];}
Q_PROPERTY(float System_Pad2            READ System_Pad2        NOTIFY onHolleyDataChanged) const float& System_Pad2()          {return m_data[127];}
Q_PROPERTY(float System_Pad3            READ System_Pad3        NOTIFY onHolleyDataChanged) const float& System_Pad3()          {return m_data[128];}
Q_PROPERTY(float System_Pad4            READ System_Pad4        NOTIFY onHolleyDataChanged) const float& System_Pad4()          {return m_data[129];}
Q_PROPERTY(float Boost_Gear             READ Boost_Gear         NOTIFY onHolleyDataChanged) const float& Boost_Gear()           {return m_data[130];}
Q_PROPERTY(float Boost_Stage            READ Boost_Stage        NOTIFY onHolleyDataChanged) const float& Boost_Stage()          {return m_data[131];}
Q_PROPERTY(float Boost                  READ Boost              NOTIFY onHolleyDataChanged) const float& Boost()                {return m_data[132];}
Q_PROPERTY(float Boost_Speed            READ Boost_Speed        NOTIFY onHolleyDataChanged) const float& Boost_Speed()          {return m_data[133];}
Q_PROPERTY(float Boost_Time             READ Boost_Time         NOTIFY onHolleyDataChanged) const float& Boost_Time()           {return m_data[134];}
Q_PROPERTY(float Target_Boost           READ Target_Boost       NOTIFY onHolleyDataChanged) const float& Target_Boost()         {return m_data[135];}
Q_PROPERTY(float Trans_Brake            READ Trans_Brake        NOTIFY onHolleyDataChanged) const float& Trans_Brake()          {return m_data[136];}
Q_PROPERTY(float Boost_Scramble_Pos     READ Boost_Scramble_Pos NOTIFY onHolleyDataChanged) const float& Boost_Scramble_Pos()   {return m_data[137];}
Q_PROPERTY(float Boost_Scramble_Neg     READ Boost_Scramble_Neg NOTIFY onHolleyDataChanged) const float& Boost_Scramble_Neg()   {return m_data[138];}
Q_PROPERTY(float Manual_Boost_Build     READ Manual_Boost_Build NOTIFY onHolleyDataChanged) const float& Manual_Boost_Build()   {return m_data[139];}
Q_PROPERTY(float Manual_Boost_Reset     READ Manual_Boost_Reset NOTIFY onHolleyDataChanged) const float& Manual_Boost_Reset()   {return m_data[140];}
Q_PROPERTY(float Boost_Build            READ Boost_Build        NOTIFY onHolleyDataChanged) const float& Boost_Build()          {return m_data[141];}
Q_PROPERTY(float Boost_Solenoid_Duty    READ Boost_Solenoid_Duty NOTIFY onHolleyDataChanged) const float& Boost_Solenoid_Duty() {return m_data[142];}
Q_PROPERTY(float Boost_Safety           READ Boost_Safety       NOTIFY onHolleyDataChanged) const float& Boost_Safety()         {return m_data[143];}
Q_PROPERTY(float Boost_Master_Enbl      READ Boost_Master_Enbl  NOTIFY onHolleyDataChanged) const float& Boost_Master_Enbl()    {return m_data[144];}
Q_PROPERTY(float Boost_Man_Shift_Inp    READ Boost_Man_Shift_Inp NOTIFY onHolleyDataChanged) const float& Boost_Man_Shift_Inp() {return m_data[145];}
Q_PROPERTY(float Boost_Man_Stage_Inp    READ Boost_Man_Stage_Inp NOTIFY onHolleyDataChanged) const float& Boost_Man_Stage_Inp() {return m_data[146];}
Q_PROPERTY(float Boost_Fill_Sol_DC      READ Boost_Fill_Sol_DC  NOTIFY onHolleyDataChanged) const float& Boost_Fill_Sol_DC()    {return m_data[147];}
Q_PROPERTY(float Boost_Vent_Sol_DC      READ Boost_Vent_Sol_DC  NOTIFY onHolleyDataChanged) const float& Boost_Vent_Sol_DC()    {return m_data[148];}
Q_PROPERTY(float W_M_Injection          READ W_M_Injection      NOTIFY onHolleyDataChanged) const float& W_M_Injection()        {return m_data[149];}
Q_PROPERTY(float W_M_Manual_Enable      READ W_M_Manual_Enable  NOTIFY onHolleyDataChanged) const float& W_M_Manual_Enable()    {return m_data[150];}
Q_PROPERTY(float W_M_Low_Fluid          READ W_M_Low_Fluid      NOTIFY onHolleyDataChanged) const float& W_M_Low_Fluid()        {return m_data[151];}
Q_PROPERTY(float W_M_Pump               READ W_M_Pump           NOTIFY onHolleyDataChanged) const float& W_M_Pump()             {return m_data[152];}
Q_PROPERTY(float W_M_Sol_1_Flow         READ W_M_Sol_1_Flow     NOTIFY onHolleyDataChanged) const float& W_M_Sol_1_Flow()       {return m_data[153];}
Q_PROPERTY(float W_M_Sol_2_Flow         READ W_M_Sol_2_Flow     NOTIFY onHolleyDataChanged) const float& W_M_Sol_2_Flow()       {return m_data[154];}
Q_PROPERTY(float W_M_Flow_Total         READ W_M_Flow_Total     NOTIFY onHolleyDataChanged) const float& W_M_Flow_Total()       {return m_data[155];}
Q_PROPERTY(float W_M_Sol_1_DC           READ W_M_Sol_1_DC       NOTIFY onHolleyDataChanged) const float& W_M_Sol_1_DC()         {return m_data[156];}
Q_PROPERTY(float W_M_Sol_2_DC           READ W_M_Sol_2_DC       NOTIFY onHolleyDataChanged) const float& W_M_Sol_2_DC()         {return m_data[157];}
Q_PROPERTY(float W_M_Pad1               READ W_M_Pad1           NOTIFY onHolleyDataChanged) const float& W_M_Pad1()             {return m_data[158];}
Q_PROPERTY(float W_M_Pad2               READ W_M_Pad2           NOTIFY onHolleyDataChanged) const float& W_M_Pad2()             {return m_data[159];}
Q_PROPERTY(float N2O_Stange_1           READ N2O_Stange_1       NOTIFY onHolleyDataChanged) const float& N2O_Stange_1()         {return m_data[160];}
Q_PROPERTY(float N2O_Stange_2           READ N2O_Stange_2       NOTIFY onHolleyDataChanged) const float& N2O_Stange_2()         {return m_data[161];}
Q_PROPERTY(float N2O_Stange_3           READ N2O_Stange_3       NOTIFY onHolleyDataChanged) const float& N2O_Stange_3()         {return m_data[162];}
Q_PROPERTY(float N2O_Stange_4           READ N2O_Stange_4       NOTIFY onHolleyDataChanged) const float& N2O_Stange_4()         {return m_data[163];}
Q_PROPERTY(float N2O_Stange_5           READ N2O_Stange_5       NOTIFY onHolleyDataChanged) const float& N2O_Stange_5()         {return m_data[164];}
Q_PROPERTY(float N2O_Stange_6           READ N2O_Stange_6       NOTIFY onHolleyDataChanged) const float& N2O_Stange_6()         {return m_data[165];}
Q_PROPERTY(float N2O_Stange_7           READ N2O_Stange_7       NOTIFY onHolleyDataChanged) const float& N2O_Stange_7()         {return m_data[166];}
Q_PROPERTY(float N2O_Stange_8           READ N2O_Stange_8       NOTIFY onHolleyDataChanged) const float& N2O_Stange_8()         {return m_data[167];}
Q_PROPERTY(float GPO_1                  READ GPO_1              NOTIFY onHolleyDataChanged) const float& GPO_1()                {return m_data[168];}
Q_PROPERTY(float GPO_2                  READ GPO_2              NOTIFY onHolleyDataChanged) const float& GPO_2()                {return m_data[169];}
Q_PROPERTY(float GPO_3                  READ GPO_3              NOTIFY onHolleyDataChanged) const float& GPO_3()                {return m_data[170];}
Q_PROPERTY(float GPO_4                  READ GPO_4              NOTIFY onHolleyDataChanged) const float& GPO_4()                {return m_data[171];}
Q_PROPERTY(float GPO_5                  READ GPO_5              NOTIFY onHolleyDataChanged) const float& GPO_5()                {return m_data[172];}
Q_PROPERTY(float GPO_6                  READ GPO_6              NOTIFY onHolleyDataChanged) const float& GPO_6()                {return m_data[173];}
Q_PROPERTY(float GPO_7                  READ GPO_7              NOTIFY onHolleyDataChanged) const float& GPO_7()                {return m_data[174];}
Q_PROPERTY(float GPO_8                  READ GPO_8              NOTIFY onHolleyDataChanged) const float& GPO_8()                {return m_data[175];}
Q_PROPERTY(float N2O_Enabled            READ N2O_Enabled        NOTIFY onHolleyDataChanged) const float& N2O_Enabled()          {return m_data[176];}
Q_PROPERTY(float N2O_Input_1            READ N2O_Input_1        NOTIFY onHolleyDataChanged) const float& N2O_Input_1()          {return m_data[177];}
Q_PROPERTY(float N2O_Input_2            READ N2O_Input_2        NOTIFY onHolleyDataChanged) const float& N2O_Input_2()          {return m_data[178];}
Q_PROPERTY(float N2O_Input_3            READ N2O_Input_3        NOTIFY onHolleyDataChanged) const float& N2O_Input_3()          {return m_data[179];}
Q_PROPERTY(float N2O_Input_4            READ N2O_Input_4        NOTIFY onHolleyDataChanged) const float& N2O_Input_4()          {return m_data[180];}
Q_PROPERTY(float N2O_Input_5            READ N2O_Input_5        NOTIFY onHolleyDataChanged) const float& N2O_Input_5()          {return m_data[181];}
Q_PROPERTY(float N2O_Input_6            READ N2O_Input_6        NOTIFY onHolleyDataChanged) const float& N2O_Input_6()          {return m_data[182];}
Q_PROPERTY(float N2O_Input_7            READ N2O_Input_7        NOTIFY onHolleyDataChanged) const float& N2O_Input_7()          {return m_data[183];}
Q_PROPERTY(float N2O_Input_8            READ N2O_Input_8        NOTIFY onHolleyDataChanged) const float& N2O_Input_8()          {return m_data[184];}
Q_PROPERTY(float N2O_Purge              READ N2O_Purge          NOTIFY onHolleyDataChanged) const float& N2O_Purge()            {return m_data[185];}
Q_PROPERTY(float N2O_Lean_Cutoff        READ N2O_Lean_Cutoff    NOTIFY onHolleyDataChanged) const float& N2O_Lean_Cutoff()      {return m_data[186];}
Q_PROPERTY(float N2O_Rich_Cutoff        READ N2O_Rich_Cutoff    NOTIFY onHolleyDataChanged) const float& N2O_Rich_Cutoff()      {return m_data[187];}
Q_PROPERTY(float N2O_RPM_Cutoff         READ N2O_RPM_Cutoff     NOTIFY onHolleyDataChanged) const float& N2O_RPM_Cutoff()       {return m_data[188];}
Q_PROPERTY(float N2O_MaP_Cutoff         READ N2O_MaP_Cutoff     NOTIFY onHolleyDataChanged) const float& N2O_MaP_Cutoff()       {return m_data[189];}
Q_PROPERTY(float N2O_Purge_Output       READ N2O_Purge_Output   NOTIFY onHolleyDataChanged) const float& N2O_Purge_Output()     {return m_data[190];}
Q_PROPERTY(float N2O_Dry_Fuel_1         READ N2O_Dry_Fuel_1     NOTIFY onHolleyDataChanged) const float& N2O_Dry_Fuel_1()       {return m_data[191];}
Q_PROPERTY(float N2O_Dry_Fuel_2         READ N2O_Dry_Fuel_2     NOTIFY onHolleyDataChanged) const float& N2O_Dry_Fuel_2()       {return m_data[192];}
Q_PROPERTY(float N2O_Dry_Fuel_3         READ N2O_Dry_Fuel_3     NOTIFY onHolleyDataChanged) const float& N2O_Dry_Fuel_3()       {return m_data[193];}
Q_PROPERTY(float N2O_Dry_Fuel_4         READ N2O_Dry_Fuel_4     NOTIFY onHolleyDataChanged) const float& N2O_Dry_Fuel_4()       {return m_data[194];}
Q_PROPERTY(float N2O_Dry_Fuel_5         READ N2O_Dry_Fuel_5     NOTIFY onHolleyDataChanged) const float& N2O_Dry_Fuel_5()       {return m_data[195];}
Q_PROPERTY(float N2O_Dry_Fuel_6         READ N2O_Dry_Fuel_6     NOTIFY onHolleyDataChanged) const float& N2O_Dry_Fuel_6()       {return m_data[196];}
Q_PROPERTY(float N2O_Dry_Fuel_7         READ N2O_Dry_Fuel_7     NOTIFY onHolleyDataChanged) const float& N2O_Dry_Fuel_7()       {return m_data[197];}
Q_PROPERTY(float N2O_Dry_Fuel_8         READ N2O_Dry_Fuel_8     NOTIFY onHolleyDataChanged) const float& N2O_Dry_Fuel_8()       {return m_data[198];}
Q_PROPERTY(float N2O_Tmg_Mod_1          READ N2O_Tmg_Mod_1      NOTIFY onHolleyDataChanged) const float& N2O_Tmg_Mod_1()        {return m_data[199];}
Q_PROPERTY(float N2O_Tmg_Mod_2          READ N2O_Tmg_Mod_2      NOTIFY onHolleyDataChanged) const float& N2O_Tmg_Mod_2()        {return m_data[200];}
Q_PROPERTY(float N2O_Tmg_Mod_3          READ N2O_Tmg_Mod_3      NOTIFY onHolleyDataChanged) const float& N2O_Tmg_Mod_3()        {return m_data[201];}
Q_PROPERTY(float N2O_Tmg_Mod_4          READ N2O_Tmg_Mod_4      NOTIFY onHolleyDataChanged) const float& N2O_Tmg_Mod_4()        {return m_data[202];}
Q_PROPERTY(float N2O_Tmg_Mod_5          READ N2O_Tmg_Mod_5      NOTIFY onHolleyDataChanged) const float& N2O_Tmg_Mod_5()        {return m_data[203];}
Q_PROPERTY(float N2O_Tmg_Mod_6          READ N2O_Tmg_Mod_6      NOTIFY onHolleyDataChanged) const float& N2O_Tmg_Mod_6()        {return m_data[204];}
Q_PROPERTY(float N2O_Tmg_Mod_7          READ N2O_Tmg_Mod_7      NOTIFY onHolleyDataChanged) const float& N2O_Tmg_Mod_7()        {return m_data[205];}
Q_PROPERTY(float N2O_Tmg_Mod_8          READ N2O_Tmg_Mod_8      NOTIFY onHolleyDataChanged) const float& N2O_Tmg_Mod_8()        {return m_data[206];}
Q_PROPERTY(float N2O_Timer_1            READ N2O_Timer_1        NOTIFY onHolleyDataChanged) const float& N2O_Timer_1()          {return m_data[207];}
Q_PROPERTY(float N2O_Timer_2            READ N2O_Timer_2        NOTIFY onHolleyDataChanged) const float& N2O_Timer_2()          {return m_data[208];}
Q_PROPERTY(float N2O_Timer_3            READ N2O_Timer_3        NOTIFY onHolleyDataChanged) const float& N2O_Timer_3()          {return m_data[209];}
Q_PROPERTY(float N2O_Timer_4            READ N2O_Timer_4        NOTIFY onHolleyDataChanged) const float& N2O_Timer_4()          {return m_data[210];}
Q_PROPERTY(float N2O_Timer_5            READ N2O_Timer_5        NOTIFY onHolleyDataChanged) const float& N2O_Timer_5()          {return m_data[211];}
Q_PROPERTY(float N2O_Timer_6            READ N2O_Timer_6        NOTIFY onHolleyDataChanged) const float& N2O_Timer_6()          {return m_data[212];}
Q_PROPERTY(float N2O_Timer_7            READ N2O_Timer_7        NOTIFY onHolleyDataChanged) const float& N2O_Timer_7()          {return m_data[213];}
Q_PROPERTY(float N2O_Timer_8            READ N2O_Timer_8        NOTIFY onHolleyDataChanged) const float& N2O_Timer_8()          {return m_data[214];}
Q_PROPERTY(float N2O_Pad1               READ N2O_Pad1           NOTIFY onHolleyDataChanged) const float& N2O_Pad1()             {return m_data[215];}
Q_PROPERTY(float N2O_Pad2               READ N2O_Pad2           NOTIFY onHolleyDataChanged) const float& N2O_Pad2()             {return m_data[216];}
Q_PROPERTY(float N2O_Pad3               READ N2O_Pad3           NOTIFY onHolleyDataChanged) const float& N2O_Pad3()             {return m_data[217];}
Q_PROPERTY(float N2O_Pad4               READ N2O_Pad4           NOTIFY onHolleyDataChanged) const float& N2O_Pad4()             {return m_data[218];}
Q_PROPERTY(float Gear                   READ Gear               NOTIFY onHolleyDataChanged) const float& Gear()                 {return m_data[219];}
Q_PROPERTY(float Speed                  READ Speed              NOTIFY onHolleyDataChanged) const float& Speed()                {return m_data[220];}
Q_PROPERTY(float Line_Pressure          READ Line_Pressure      NOTIFY onHolleyDataChanged) const float& Line_Pressure()        {return m_data[221];}
Q_PROPERTY(float Input_Shaft_Speed      READ Input_Shaft_Speed  NOTIFY onHolleyDataChanged) const float& Input_Shaft_Speed()    {return m_data[222];}
Q_PROPERTY(float Accum_Pressure         READ Accum_Pressure     NOTIFY onHolleyDataChanged) const float& Accum_Pressure()       {return m_data[223];}
Q_PROPERTY(float TCC_Duty_Cycle         READ TCC_Duty_Cycle     NOTIFY onHolleyDataChanged) const float& TCC_Duty_Cycle()       {return m_data[224];}
Q_PROPERTY(float Line_Temp              READ Line_Temp          NOTIFY onHolleyDataChanged) const float& Line_Temp()            {return m_data[225];}
Q_PROPERTY(float Torque_Time            READ Torque_Time        NOTIFY onHolleyDataChanged) const float& Torque_Time()          {return m_data[226];}
Q_PROPERTY(float Trans_Man_US_Input     READ Trans_Man_US_Input NOTIFY onHolleyDataChanged) const float& Trans_Man_US_Input()   {return m_data[227];}
Q_PROPERTY(float Trans_Man_DS_Input     READ Trans_Man_DS_Input NOTIFY onHolleyDataChanged) const float& Trans_Man_DS_Input()   {return m_data[228];}
Q_PROPERTY(float Trans_Auto_Man_In      READ Trans_Auto_Man_In  NOTIFY onHolleyDataChanged) const float& Trans_Auto_Man_In()    {return m_data[229];}
Q_PROPERTY(float Trans_Pad1             READ Trans_Pad1         NOTIFY onHolleyDataChanged) const float& Trans_Pad1()           {return m_data[230];}
Q_PROPERTY(float Trans_Pad2             READ Trans_Pad2         NOTIFY onHolleyDataChanged) const float& Trans_Pad2()           {return m_data[231];}
Q_PROPERTY(float TB_TPS_1               READ TB_TPS_1           NOTIFY onHolleyDataChanged) const float& TB_TPS_1()             {return m_data[232];}
Q_PROPERTY(float TB_TPS_2               READ TB_TPS_2           NOTIFY onHolleyDataChanged) const float& TB_TPS_2()             {return m_data[233];}
Q_PROPERTY(float Pedal_TPS_1            READ Pedal_TPS_1        NOTIFY onHolleyDataChanged) const float& Pedal_TPS_1()          {return m_data[234];}
Q_PROPERTY(float Pedal_TPS_2            READ Pedal_TPS_2        NOTIFY onHolleyDataChanged) const float& Pedal_TPS_2()          {return m_data[235];}
Q_PROPERTY(float TB2_TPS_1              READ TB2_TPS_1          NOTIFY onHolleyDataChanged) const float& TB2_TPS_1()            {return m_data[236];}
Q_PROPERTY(float TB2_TPS_2              READ TB2_TPS_2          NOTIFY onHolleyDataChanged) const float& TB2_TPS_2()            {return m_data[237];}
Q_PROPERTY(float TB_Position            READ TB_Position        NOTIFY onHolleyDataChanged) const float& TB_Position()          {return m_data[238];}
Q_PROPERTY(float TB2_Position           READ TB2_Position       NOTIFY onHolleyDataChanged) const float& TB2_Position()         {return m_data[239];}
Q_PROPERTY(float Brake_Pedal            READ Brake_Pedal        NOTIFY onHolleyDataChanged) const float& Brake_Pedal()          {return m_data[240];}
Q_PROPERTY(float DBW_Pad2               READ DBW_Pad2           NOTIFY onHolleyDataChanged) const float& DBW_Pad2()             {return m_data[241];}
Q_PROPERTY(float Diag_1                 READ Diag_1             NOTIFY onHolleyDataChanged) const float& Diag_1()               {return m_data[242];}
Q_PROPERTY(float Diag_2                 READ Diag_2             NOTIFY onHolleyDataChanged) const float& Diag_2()               {return m_data[243];}
Q_PROPERTY(float Diag_3                 READ Diag_3             NOTIFY onHolleyDataChanged) const float& Diag_3()               {return m_data[244];}
Q_PROPERTY(float Diag_4                 READ Diag_4             NOTIFY onHolleyDataChanged) const float& Diag_4()               {return m_data[245];}
Q_PROPERTY(float Diag_5                 READ Diag_5             NOTIFY onHolleyDataChanged) const float& Diag_5()               {return m_data[246];}
Q_PROPERTY(float Diag_6                 READ Diag_6             NOTIFY onHolleyDataChanged) const float& Diag_6()               {return m_data[247];}
Q_PROPERTY(float Diag_7                 READ Diag_7             NOTIFY onHolleyDataChanged) const float& Diag_7()               {return m_data[248];}
Q_PROPERTY(float Diag_8                 READ Diag_8             NOTIFY onHolleyDataChanged) const float& Diag_8()               {return m_data[249];}
Q_PROPERTY(float Diag_9                 READ Diag_9             NOTIFY onHolleyDataChanged) const float& Diag_9()               {return m_data[250];}
Q_PROPERTY(float Diag_10                READ Diag_10            NOTIFY onHolleyDataChanged) const float& Diag_10()              {return m_data[251];}
Q_PROPERTY(float Diag_11                READ Diag_11            NOTIFY onHolleyDataChanged) const float& Diag_11()              {return m_data[252];}
Q_PROPERTY(float Diag_12                READ Diag_12            NOTIFY onHolleyDataChanged) const float& Diag_12()              {return m_data[253];}
Q_PROPERTY(float Diag_13                READ Diag_13            NOTIFY onHolleyDataChanged) const float& Diag_13()              {return m_data[254];}
Q_PROPERTY(float Diag_14                READ Diag_14            NOTIFY onHolleyDataChanged) const float& Diag_14()              {return m_data[255];}
Q_PROPERTY(float Diag_15                READ Diag_15            NOTIFY onHolleyDataChanged) const float& Diag_15()              {return m_data[256];}
Q_PROPERTY(float Diag_16                READ Diag_16            NOTIFY onHolleyDataChanged) const float& Diag_16()              {return m_data[257];}
Q_PROPERTY(float Diag_17                READ Diag_17            NOTIFY onHolleyDataChanged) const float& Diag_17()              {return m_data[258];}
Q_PROPERTY(float Diag_18                READ Diag_18            NOTIFY onHolleyDataChanged) const float& Diag_18()              {return m_data[259];}
Q_PROPERTY(float Diag_19                READ Diag_19            NOTIFY onHolleyDataChanged) const float& Diag_19()              {return m_data[260];}
Q_PROPERTY(float Diag_20                READ Diag_20            NOTIFY onHolleyDataChanged) const float& Diag_20()              {return m_data[261];}
Q_PROPERTY(float ATLaunch_Input         READ ATLaunch_Input     NOTIFY onHolleyDataChanged) const float& ATLaunch_Input()       {return m_data[262];}
Q_PROPERTY(float ATShift_Input          READ ATShift_Input      NOTIFY onHolleyDataChanged) const float& ATShift_Input()        {return m_data[263];}
Q_PROPERTY(float ATManual_Reset         READ ATManual_Reset     NOTIFY onHolleyDataChanged) const float& ATManual_Reset()       {return m_data[264];}
Q_PROPERTY(float ATGear                 READ ATGear             NOTIFY onHolleyDataChanged) const float& ATGear()               {return m_data[265];}
Q_PROPERTY(float AT1D_1                 READ AT1D_1             NOTIFY onHolleyDataChanged) const float& AT1D_1()               {return m_data[266];}
Q_PROPERTY(float AT1D_2                 READ AT1D_2             NOTIFY onHolleyDataChanged) const float& AT1D_2()               {return m_data[267];}
Q_PROPERTY(float AT1D_3                 READ AT1D_3             NOTIFY onHolleyDataChanged) const float& AT1D_3()               {return m_data[268];}
Q_PROPERTY(float AT1D_4                 READ AT1D_4             NOTIFY onHolleyDataChanged) const float& AT1D_4()               {return m_data[269];}
Q_PROPERTY(float AT1D_5                 READ AT1D_5             NOTIFY onHolleyDataChanged) const float& AT1D_5()               {return m_data[270];}
Q_PROPERTY(float AT1D_6                 READ AT1D_6             NOTIFY onHolleyDataChanged) const float& AT1D_6()               {return m_data[271];}
Q_PROPERTY(float AT1D_7                 READ AT1D_7             NOTIFY onHolleyDataChanged) const float& AT1D_7()               {return m_data[272];}
Q_PROPERTY(float AT1D_8                 READ AT1D_8             NOTIFY onHolleyDataChanged) const float& AT1D_8()               {return m_data[273];}
Q_PROPERTY(float AT2D_1                 READ AT2D_1             NOTIFY onHolleyDataChanged) const float& AT2D_1()               {return m_data[274];}
Q_PROPERTY(float AT2D_2                 READ AT2D_2             NOTIFY onHolleyDataChanged) const float& AT2D_2()               {return m_data[275];}
Q_PROPERTY(float AT2D_3                 READ AT2D_3             NOTIFY onHolleyDataChanged) const float& AT2D_3()               {return m_data[276];}
Q_PROPERTY(float AT2D_4                 READ AT2D_4             NOTIFY onHolleyDataChanged) const float& AT2D_4()               {return m_data[277];}
Q_PROPERTY(float AT2D_5                 READ AT2D_5             NOTIFY onHolleyDataChanged) const float& AT2D_5()               {return m_data[278];}
Q_PROPERTY(float AT2D_6                 READ AT2D_6             NOTIFY onHolleyDataChanged) const float& AT2D_6()               {return m_data[279];}
Q_PROPERTY(float AT2D_7                 READ AT2D_7             NOTIFY onHolleyDataChanged) const float& AT2D_7()               {return m_data[280];}
Q_PROPERTY(float AT2D_8                 READ AT2D_8             NOTIFY onHolleyDataChanged) const float& AT2D_8()               {return m_data[281];}
Q_PROPERTY(float AT1DGear_1             READ AT1DGear_1         NOTIFY onHolleyDataChanged) const float& AT1DGear_1()           {return m_data[282];}
Q_PROPERTY(float AT1DGear_2             READ AT1DGear_2         NOTIFY onHolleyDataChanged) const float& AT1DGear_2()           {return m_data[283];}
Q_PROPERTY(float AT1DGear_3             READ AT1DGear_3         NOTIFY onHolleyDataChanged) const float& AT1DGear_3()           {return m_data[284];}
Q_PROPERTY(float AT1DGear_4             READ AT1DGear_4         NOTIFY onHolleyDataChanged) const float& AT1DGear_4()           {return m_data[285];}
Q_PROPERTY(float AT1DGear_5             READ AT1DGear_5         NOTIFY onHolleyDataChanged) const float& AT1DGear_5()           {return m_data[286];}
Q_PROPERTY(float AT1DGear_6             READ AT1DGear_6         NOTIFY onHolleyDataChanged) const float& AT1DGear_6()           {return m_data[287];}
Q_PROPERTY(float AT1DGear_7             READ AT1DGear_7         NOTIFY onHolleyDataChanged) const float& AT1DGear_7()           {return m_data[288];}
Q_PROPERTY(float AT1DGear_8             READ AT1DGear_8         NOTIFY onHolleyDataChanged) const float& AT1DGear_8()           {return m_data[289];}
Q_PROPERTY(float AT2DGear_1             READ AT2DGear_1         NOTIFY onHolleyDataChanged) const float& AT2DGear_1()           {return m_data[290];}
Q_PROPERTY(float AT2DGear_2             READ AT2DGear_2         NOTIFY onHolleyDataChanged) const float& AT2DGear_2()           {return m_data[291];}
Q_PROPERTY(float AT2DGear_3             READ AT2DGear_3         NOTIFY onHolleyDataChanged) const float& AT2DGear_3()           {return m_data[292];}
Q_PROPERTY(float AT2DGear_4             READ AT2DGear_4         NOTIFY onHolleyDataChanged) const float& AT2DGear_4()           {return m_data[293];}
Q_PROPERTY(float AT2DGear_5             READ AT2DGear_5         NOTIFY onHolleyDataChanged) const float& AT2DGear_5()           {return m_data[294];}
Q_PROPERTY(float AT2DGear_6             READ AT2DGear_6         NOTIFY onHolleyDataChanged) const float& AT2DGear_6()           {return m_data[295];}
Q_PROPERTY(float AT2DGear_7             READ AT2DGear_7         NOTIFY onHolleyDataChanged) const float& AT2DGear_7()           {return m_data[296];}
Q_PROPERTY(float AT2DGear_8             READ AT2DGear_8         NOTIFY onHolleyDataChanged) const float& AT2DGear_8()           {return m_data[297];}
Q_PROPERTY(float Input_1                READ Input_1            NOTIFY onHolleyDataChanged) const float& Input_1()              {return m_data[298];}
Q_PROPERTY(float Input_2                READ Input_2            NOTIFY onHolleyDataChanged) const float& Input_2()              {return m_data[299];}
Q_PROPERTY(float Input_3                READ Input_3            NOTIFY onHolleyDataChanged) const float& Input_3()              {return m_data[300];}
Q_PROPERTY(float Input_4                READ Input_4            NOTIFY onHolleyDataChanged) const float& Input_4()              {return m_data[301];}
Q_PROPERTY(float Input_5                READ Input_5            NOTIFY onHolleyDataChanged) const float& Input_5()              {return m_data[302];}
Q_PROPERTY(float Input_6                READ Input_6            NOTIFY onHolleyDataChanged) const float& Input_6()              {return m_data[303];}
Q_PROPERTY(float Input_7                READ Input_7            NOTIFY onHolleyDataChanged) const float& Input_7()              {return m_data[304];}
Q_PROPERTY(float Input_8                READ Input_8            NOTIFY onHolleyDataChanged) const float& Input_8()              {return m_data[305];}
Q_PROPERTY(float Input_9                READ Input_9            NOTIFY onHolleyDataChanged) const float& Input_9()              {return m_data[306];}
Q_PROPERTY(float Input_10               READ Input_10           NOTIFY onHolleyDataChanged) const float& Input_10()             {return m_data[307];}
Q_PROPERTY(float Input_11               READ Input_11           NOTIFY onHolleyDataChanged) const float& Input_11()             {return m_data[308];}
Q_PROPERTY(float Input_12               READ Input_12           NOTIFY onHolleyDataChanged) const float& Input_12()             {return m_data[309];}
Q_PROPERTY(float Input_13               READ Input_13           NOTIFY onHolleyDataChanged) const float& Input_13()             {return m_data[310];}
Q_PROPERTY(float Input_14               READ Input_14           NOTIFY onHolleyDataChanged) const float& Input_14()             {return m_data[311];}
Q_PROPERTY(float Input_15               READ Input_15           NOTIFY onHolleyDataChanged) const float& Input_15()             {return m_data[312];}
Q_PROPERTY(float Input_16               READ Input_16           NOTIFY onHolleyDataChanged) const float& Input_16()             {return m_data[313];}
Q_PROPERTY(float Input_17               READ Input_17           NOTIFY onHolleyDataChanged) const float& Input_17()             {return m_data[314];}
Q_PROPERTY(float Input_18               READ Input_18           NOTIFY onHolleyDataChanged) const float& Input_18()             {return m_data[315];}
Q_PROPERTY(float Input_19               READ Input_19           NOTIFY onHolleyDataChanged) const float& Input_19()             {return m_data[316];}
Q_PROPERTY(float Input_20               READ Input_20           NOTIFY onHolleyDataChanged) const float& Input_20()             {return m_data[317];}
Q_PROPERTY(float Input_21               READ Input_21           NOTIFY onHolleyDataChanged) const float& Input_21()             {return m_data[318];}
Q_PROPERTY(float Input_22               READ Input_22           NOTIFY onHolleyDataChanged) const float& Input_22()             {return m_data[319];}
Q_PROPERTY(float Input_23               READ Input_23           NOTIFY onHolleyDataChanged) const float& Input_23()             {return m_data[320];}
Q_PROPERTY(float Input_24               READ Input_24           NOTIFY onHolleyDataChanged) const float& Input_24()             {return m_data[321];}
Q_PROPERTY(float Input_25               READ Input_25           NOTIFY onHolleyDataChanged) const float& Input_25()             {return m_data[322];}
Q_PROPERTY(float Input_26               READ Input_26           NOTIFY onHolleyDataChanged) const float& Input_26()             {return m_data[323];}
Q_PROPERTY(float Input_27               READ Input_27           NOTIFY onHolleyDataChanged) const float& Input_27()             {return m_data[324];}
Q_PROPERTY(float Input_28               READ Input_28           NOTIFY onHolleyDataChanged) const float& Input_28()             {return m_data[325];}
Q_PROPERTY(float Input_29               READ Input_29           NOTIFY onHolleyDataChanged) const float& Input_29()             {return m_data[326];}
Q_PROPERTY(float Input_30               READ Input_30           NOTIFY onHolleyDataChanged) const float& Input_30()             {return m_data[327];}
Q_PROPERTY(float Input_31               READ Input_31           NOTIFY onHolleyDataChanged) const float& Input_31()             {return m_data[328];}
Q_PROPERTY(float Input_32               READ Input_32           NOTIFY onHolleyDataChanged) const float& Input_32()             {return m_data[329];}
Q_PROPERTY(float Input_33               READ Input_33           NOTIFY onHolleyDataChanged) const float& Input_33()             {return m_data[330];}
Q_PROPERTY(float Input_34               READ Input_34           NOTIFY onHolleyDataChanged) const float& Input_34()             {return m_data[331];}
Q_PROPERTY(float Input_35               READ Input_35           NOTIFY onHolleyDataChanged) const float& Input_35()             {return m_data[332];}
Q_PROPERTY(float Input_36               READ Input_36           NOTIFY onHolleyDataChanged) const float& Input_36()             {return m_data[333];}
Q_PROPERTY(float Input_37               READ Input_37           NOTIFY onHolleyDataChanged) const float& Input_37()             {return m_data[334];}
Q_PROPERTY(float Input_38               READ Input_38           NOTIFY onHolleyDataChanged) const float& Input_38()             {return m_data[335];}
Q_PROPERTY(float Input_39               READ Input_39           NOTIFY onHolleyDataChanged) const float& Input_39()             {return m_data[336];}
Q_PROPERTY(float Input_40               READ Input_40           NOTIFY onHolleyDataChanged) const float& Input_40()             {return m_data[337];}
Q_PROPERTY(float Input_41               READ Input_41           NOTIFY onHolleyDataChanged) const float& Input_41()             {return m_data[338];}
Q_PROPERTY(float Input_42               READ Input_42           NOTIFY onHolleyDataChanged) const float& Input_42()             {return m_data[339];}
Q_PROPERTY(float Input_43               READ Input_43           NOTIFY onHolleyDataChanged) const float& Input_43()             {return m_data[340];}
Q_PROPERTY(float Input_44               READ Input_44           NOTIFY onHolleyDataChanged) const float& Input_44()             {return m_data[341];}
Q_PROPERTY(float Input_45               READ Input_45           NOTIFY onHolleyDataChanged) const float& Input_45()             {return m_data[342];}
Q_PROPERTY(float Input_46               READ Input_46           NOTIFY onHolleyDataChanged) const float& Input_46()             {return m_data[343];}
Q_PROPERTY(float Input_47               READ Input_47           NOTIFY onHolleyDataChanged) const float& Input_47()             {return m_data[344];}
Q_PROPERTY(float Input_48               READ Input_48           NOTIFY onHolleyDataChanged) const float& Input_48()             {return m_data[345];}
Q_PROPERTY(float Input_49               READ Input_49           NOTIFY onHolleyDataChanged) const float& Input_49()             {return m_data[346];}
Q_PROPERTY(float Input_50               READ Input_50           NOTIFY onHolleyDataChanged) const float& Input_50()             {return m_data[347];}
Q_PROPERTY(float Input_51               READ Input_51           NOTIFY onHolleyDataChanged) const float& Input_51()             {return m_data[348];}
Q_PROPERTY(float Input_52               READ Input_52           NOTIFY onHolleyDataChanged) const float& Input_52()             {return m_data[349];}
Q_PROPERTY(float Input_53               READ Input_53           NOTIFY onHolleyDataChanged) const float& Input_53()             {return m_data[350];}
Q_PROPERTY(float Input_54               READ Input_54           NOTIFY onHolleyDataChanged) const float& Input_54()             {return m_data[351];}
Q_PROPERTY(float Input_55               READ Input_55           NOTIFY onHolleyDataChanged) const float& Input_55()             {return m_data[352];}
Q_PROPERTY(float Input_56               READ Input_56           NOTIFY onHolleyDataChanged) const float& Input_56()             {return m_data[353];}
Q_PROPERTY(float Input_57               READ Input_57           NOTIFY onHolleyDataChanged) const float& Input_57()             {return m_data[354];}
Q_PROPERTY(float Input_58               READ Input_58           NOTIFY onHolleyDataChanged) const float& Input_58()             {return m_data[355];}
Q_PROPERTY(float Input_59               READ Input_59           NOTIFY onHolleyDataChanged) const float& Input_59()             {return m_data[356];}
Q_PROPERTY(float Input_60               READ Input_60           NOTIFY onHolleyDataChanged) const float& Input_60()             {return m_data[357];}
Q_PROPERTY(float Input_61               READ Input_61           NOTIFY onHolleyDataChanged) const float& Input_61()             {return m_data[358];}
Q_PROPERTY(float Input_62               READ Input_62           NOTIFY onHolleyDataChanged) const float& Input_62()             {return m_data[359];}
Q_PROPERTY(float Input_63               READ Input_63           NOTIFY onHolleyDataChanged) const float& Input_63()             {return m_data[360];}
Q_PROPERTY(float Input_64               READ Input_64           NOTIFY onHolleyDataChanged) const float& Input_64()             {return m_data[361];}
Q_PROPERTY(float Input_65               READ Input_65           NOTIFY onHolleyDataChanged) const float& Input_65()             {return m_data[362];}
Q_PROPERTY(float Input_66               READ Input_66           NOTIFY onHolleyDataChanged) const float& Input_66()             {return m_data[363];}
Q_PROPERTY(float Input_67               READ Input_67           NOTIFY onHolleyDataChanged) const float& Input_67()             {return m_data[364];}
Q_PROPERTY(float Input_68               READ Input_68           NOTIFY onHolleyDataChanged) const float& Input_68()             {return m_data[365];}
Q_PROPERTY(float Input_69               READ Input_69           NOTIFY onHolleyDataChanged) const float& Input_69()             {return m_data[366];}
Q_PROPERTY(float Input_70               READ Input_70           NOTIFY onHolleyDataChanged) const float& Input_70()             {return m_data[367];}
Q_PROPERTY(float Input_71               READ Input_71           NOTIFY onHolleyDataChanged) const float& Input_71()             {return m_data[368];}
Q_PROPERTY(float Input_72               READ Input_72           NOTIFY onHolleyDataChanged) const float& Input_72()             {return m_data[369];}
Q_PROPERTY(float Input_73               READ Input_73           NOTIFY onHolleyDataChanged) const float& Input_73()             {return m_data[370];}
Q_PROPERTY(float Input_74               READ Input_74           NOTIFY onHolleyDataChanged) const float& Input_74()             {return m_data[371];}
Q_PROPERTY(float Input_75               READ Input_75           NOTIFY onHolleyDataChanged) const float& Input_75()             {return m_data[372];}
Q_PROPERTY(float Input_76               READ Input_76           NOTIFY onHolleyDataChanged) const float& Input_76()             {return m_data[373];}
Q_PROPERTY(float Input_77               READ Input_77           NOTIFY onHolleyDataChanged) const float& Input_77()             {return m_data[374];}
Q_PROPERTY(float Input_78               READ Input_78           NOTIFY onHolleyDataChanged) const float& Input_78()             {return m_data[375];}
Q_PROPERTY(float Input_79               READ Input_79           NOTIFY onHolleyDataChanged) const float& Input_79()             {return m_data[376];}
Q_PROPERTY(float Input_80               READ Input_80           NOTIFY onHolleyDataChanged) const float& Input_80()             {return m_data[377];}
Q_PROPERTY(float Output_1               READ Output_1           NOTIFY onHolleyDataChanged) const float& Output_1()             {return m_data[378];}
Q_PROPERTY(float Output_2               READ Output_2           NOTIFY onHolleyDataChanged) const float& Output_2()             {return m_data[379];}
Q_PROPERTY(float Output_3               READ Output_3           NOTIFY onHolleyDataChanged) const float& Output_3()             {return m_data[380];}
Q_PROPERTY(float Output_4               READ Output_4           NOTIFY onHolleyDataChanged) const float& Output_4()             {return m_data[381];}
Q_PROPERTY(float Output_5               READ Output_5           NOTIFY onHolleyDataChanged) const float& Output_5()             {return m_data[382];}
Q_PROPERTY(float Output_6               READ Output_6           NOTIFY onHolleyDataChanged) const float& Output_6()             {return m_data[383];}
Q_PROPERTY(float Output_7               READ Output_7           NOTIFY onHolleyDataChanged) const float& Output_7()             {return m_data[384];}
Q_PROPERTY(float Output_8               READ Output_8           NOTIFY onHolleyDataChanged) const float& Output_8()             {return m_data[385];}
Q_PROPERTY(float Output_9               READ Output_9           NOTIFY onHolleyDataChanged) const float& Output_9()             {return m_data[386];}
Q_PROPERTY(float Output_10              READ Output_10          NOTIFY onHolleyDataChanged) const float& Output_10()            {return m_data[387];}
Q_PROPERTY(float Output_11              READ Output_11          NOTIFY onHolleyDataChanged) const float& Output_11()            {return m_data[388];}
Q_PROPERTY(float Output_12              READ Output_12          NOTIFY onHolleyDataChanged) const float& Output_12()            {return m_data[389];}
Q_PROPERTY(float Output_13              READ Output_13          NOTIFY onHolleyDataChanged) const float& Output_13()            {return m_data[390];}
Q_PROPERTY(float Output_14              READ Output_14          NOTIFY onHolleyDataChanged) const float& Output_14()            {return m_data[391];}
Q_PROPERTY(float Output_15              READ Output_15          NOTIFY onHolleyDataChanged) const float& Output_15()            {return m_data[392];}
Q_PROPERTY(float Output_16              READ Output_16          NOTIFY onHolleyDataChanged) const float& Output_16()            {return m_data[393];}
Q_PROPERTY(float Output_17              READ Output_17          NOTIFY onHolleyDataChanged) const float& Output_17()            {return m_data[394];}
Q_PROPERTY(float Output_18              READ Output_18          NOTIFY onHolleyDataChanged) const float& Output_18()            {return m_data[395];}
Q_PROPERTY(float Output_19              READ Output_19          NOTIFY onHolleyDataChanged) const float& Output_19()            {return m_data[396];}
Q_PROPERTY(float Output_20              READ Output_20          NOTIFY onHolleyDataChanged) const float& Output_20()            {return m_data[397];}
Q_PROPERTY(float Output_21              READ Output_21          NOTIFY onHolleyDataChanged) const float& Output_21()            {return m_data[398];}
Q_PROPERTY(float Output_22              READ Output_22          NOTIFY onHolleyDataChanged) const float& Output_22()            {return m_data[399];}
Q_PROPERTY(float Output_23              READ Output_23          NOTIFY onHolleyDataChanged) const float& Output_23()            {return m_data[400];}
Q_PROPERTY(float Output_24              READ Output_24          NOTIFY onHolleyDataChanged) const float& Output_24()            {return m_data[401];}
Q_PROPERTY(float Output_25              READ Output_25          NOTIFY onHolleyDataChanged) const float& Output_25()            {return m_data[402];}
Q_PROPERTY(float Output_26              READ Output_26          NOTIFY onHolleyDataChanged) const float& Output_26()            {return m_data[403];}
Q_PROPERTY(float Output_27              READ Output_27          NOTIFY onHolleyDataChanged) const float& Output_27()            {return m_data[404];}
Q_PROPERTY(float Output_28              READ Output_28          NOTIFY onHolleyDataChanged) const float& Output_28()            {return m_data[405];}
Q_PROPERTY(float Output_29              READ Output_29          NOTIFY onHolleyDataChanged) const float& Output_29()            {return m_data[406];}
Q_PROPERTY(float Output_30              READ Output_30          NOTIFY onHolleyDataChanged) const float& Output_30()            {return m_data[407];}
Q_PROPERTY(float Output_31              READ Output_31          NOTIFY onHolleyDataChanged) const float& Output_31()            {return m_data[408];}
Q_PROPERTY(float Output_32              READ Output_32          NOTIFY onHolleyDataChanged) const float& Output_32()            {return m_data[409];}
Q_PROPERTY(float Output_33              READ Output_33          NOTIFY onHolleyDataChanged) const float& Output_33()            {return m_data[410];}
Q_PROPERTY(float Output_34              READ Output_34          NOTIFY onHolleyDataChanged) const float& Output_34()            {return m_data[411];}
Q_PROPERTY(float Output_35              READ Output_35          NOTIFY onHolleyDataChanged) const float& Output_35()            {return m_data[412];}
Q_PROPERTY(float Output_36              READ Output_36          NOTIFY onHolleyDataChanged) const float& Output_36()            {return m_data[413];}
Q_PROPERTY(float Output_37              READ Output_37          NOTIFY onHolleyDataChanged) const float& Output_37()            {return m_data[414];}
Q_PROPERTY(float Output_38              READ Output_38          NOTIFY onHolleyDataChanged) const float& Output_38()            {return m_data[415];}
Q_PROPERTY(float Output_39              READ Output_39          NOTIFY onHolleyDataChanged) const float& Output_39()            {return m_data[416];}
Q_PROPERTY(float Output_40              READ Output_40          NOTIFY onHolleyDataChanged) const float& Output_40()            {return m_data[417];}
Q_PROPERTY(float Output_41              READ Output_41          NOTIFY onHolleyDataChanged) const float& Output_41()            {return m_data[418];}
Q_PROPERTY(float Output_42              READ Output_42          NOTIFY onHolleyDataChanged) const float& Output_42()            {return m_data[419];}
Q_PROPERTY(float Output_43              READ Output_43          NOTIFY onHolleyDataChanged) const float& Output_43()            {return m_data[420];}
Q_PROPERTY(float Output_44              READ Output_44          NOTIFY onHolleyDataChanged) const float& Output_44()            {return m_data[421];}
Q_PROPERTY(float Output_45              READ Output_45          NOTIFY onHolleyDataChanged) const float& Output_45()            {return m_data[422];}
Q_PROPERTY(float Output_46              READ Output_46          NOTIFY onHolleyDataChanged) const float& Output_46()            {return m_data[423];}
Q_PROPERTY(float Output_47              READ Output_47          NOTIFY onHolleyDataChanged) const float& Output_47()            {return m_data[424];}
Q_PROPERTY(float Output_48              READ Output_48          NOTIFY onHolleyDataChanged) const float& Output_48()            {return m_data[425];}
Q_PROPERTY(float Output_49              READ Output_49          NOTIFY onHolleyDataChanged) const float& Output_49()            {return m_data[426];}
Q_PROPERTY(float Output_50              READ Output_50          NOTIFY onHolleyDataChanged) const float& Output_50()            {return m_data[427];}
Q_PROPERTY(float Output_51              READ Output_51          NOTIFY onHolleyDataChanged) const float& Output_51()            {return m_data[428];}
Q_PROPERTY(float Output_52              READ Output_52          NOTIFY onHolleyDataChanged) const float& Output_52()            {return m_data[429];}
Q_PROPERTY(float Output_53              READ Output_53          NOTIFY onHolleyDataChanged) const float& Output_53()            {return m_data[430];}
Q_PROPERTY(float Output_54              READ Output_54          NOTIFY onHolleyDataChanged) const float& Output_54()            {return m_data[431];}
Q_PROPERTY(float Output_55              READ Output_55          NOTIFY onHolleyDataChanged) const float& Output_55()            {return m_data[432];}
Q_PROPERTY(float Output_56              READ Output_56          NOTIFY onHolleyDataChanged) const float& Output_56()            {return m_data[433];}
Q_PROPERTY(float Output_57              READ Output_57          NOTIFY onHolleyDataChanged) const float& Output_57()            {return m_data[434];}
Q_PROPERTY(float Output_58              READ Output_58          NOTIFY onHolleyDataChanged) const float& Output_58()            {return m_data[435];}
Q_PROPERTY(float Output_59              READ Output_59          NOTIFY onHolleyDataChanged) const float& Output_59()            {return m_data[436];}
Q_PROPERTY(float Output_60              READ Output_60          NOTIFY onHolleyDataChanged) const float& Output_60()            {return m_data[437];}
Q_PROPERTY(float Output_61              READ Output_61          NOTIFY onHolleyDataChanged) const float& Output_61()            {return m_data[438];}
Q_PROPERTY(float Output_62              READ Output_62          NOTIFY onHolleyDataChanged) const float& Output_62()            {return m_data[439];}
